apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: decree-bot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bizranker/decree-bot.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: decree-bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
